name: CI

on:
#   1. 每天 00:00 UTC 时间执行
  schedule:
    - cron: '0 0 * * *'
#   2. 每次 push 到 master 分支时执行
  push:
    branches:
    - master

jobs:

    build:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Set up WireGuard Connection
            uses: Cardtonic-Technologies/ttt-wireguard@main
            with:
              WG_CONFIG: ${{ secrets.WG_CONFIG }}
      
          # 等待 5 个小时
          - name: Wait 4h no1
            run: ping -c 720 10.0.8.4

          # 再等待 4 个小时
          - name: Wait 4h no2
            run: sleep 14400
          # 再等待 4 个小时 *10
          - name: Wait 4h no3
            run: sleep 14400
          - name: Wait 4h no4
            run: sleep 14400
          - name: Wait 4h no5
              
            run: sleep 14400
          - name: Wait 4h no6
            run: sleep 14400
