name: CI

on:
#   1. 每天 00:00 UTC 时间执行
  schedule:
    - cron: '0 0 * * *'
#   2. 每次 push 到 master 分支时执行
  push:
    branches:
    - master

jobs:

    build:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          # 安装 WireGuard
          - name: Install WireGuard
            run: sudo apt-get update && sudo apt-get install -y wireguard
          

          - name: Write WireGuard Config
            run: echo "${{ secrets.WG_CONFIG }}" > /tmp/wg0.conf
    
          - name: Display WireGuard Config
            run: cat /tmp/wg0.conf
    
          - name: Set up WireGuard Connection
            run: |
              sudo ip link add wg0 type wireguard
              sudo wg setconf wg0 /tmp/wg0.conf
              sudo ip link set wg0 up
    
          # 等待 5 个小时
          - name: Wait 4h no1
            run: ping  10.0.8.4

          # 再等待 4 个小时
          - name: Wait 4h no2
            run: sleep 14400
          # 再等待 4 个小时 *10
          - name: Wait 4h no3
            run: sleep 14400
          - name: Wait 4h no4
            run: sleep 14400
          - name: Wait 4h no5
              
            run: sleep 14400
          - name: Wait 4h no6
            run: sleep 14400
