name: CI

on:
#   1. 每天 00:00 UTC 时间执行
  schedule:
    - cron: '0 0 * * *'
#   2. 每次 push 到 master 分支时执行
  push:
    branches:
    - master

jobs:

    build:
        runs-on: ubuntu-latest
    
        steps:

        - # 将base64解码后的私钥写入文件
          name: Write WireGuard Config
          run: echo "${{ secrets.WG_CONFIG }}" | base64 -d > /tmp/wg0.conf
        # 使用wg连接上私有的网络
        - name: Set up WireGuard Connection
          uses: niklaskeerl/easy-wireguard-action@v2
          with:
            WG_CONFIG_FILE: /tmp/wg0.conf
        - uses: wangsijie/setup-v2ray@v1
          with:
            config-base64: "${{ secrets.V2RAY_SERVER }}"

        # 等待 5 个小时
        - name: Wait 4h no1
          run: sleep 14400

        # 再等待 4 个小时
        - name: Wait 4h no2
          run: sleep 14400
        # 再等待 4 个小时 *10
        - name: Wait 4h no3
          run: sleep 14400
        - name: Wait 4h no4
          run: sleep 14400
        - name: Wait 4h no5
            
          run: sleep 14400
        - name: Wait 4h no6
          run: sleep 14400
