name: CI

on:
#   1. 每天 00:00 UTC 时间执行
  schedule:
    - cron: '0 0 * * *'
#   2. 每次 push 到 master 分支时执行
  push:
    branches:
    - master

jobs:

    build:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          # 安装openvpn
          - name: Write OpenVPN Auth File
            run: echo -e "gitaction\ngitaction" > auth.txt
  
          - name: Write OpenVPN Config
            run: echo "${{ secrets.OVPN_CLIENT_B64 }}" | base64 -d > client.ovpn
    
          - name: Add Auth File to OpenVPN Config
            run: echo "auth-user-pass auth.txt" >> client.ovpn
    
          - name: Install OpenVPN
            run: sudo apt-get update && sudo apt-get install -y openvpn
    
          - name: Start OpenVPN
            run: sudo openvpn --config client.ovpn &
          

          - name: Install Xray
            run: |
              wget https://github.com/xtls/xray-core/releases/latest/download/Xray-linux-64.zip
              unzip Xray-linux-64.zip
              chmod +x xray
              sudo mv xray /usr/local/bin/
              # 写入配置文件
              echo "${{ secrets.XRAY_CONFIG_B64 }}" | base64 -d > config.json
              # 启动 xray
              sudo xray run -config config.json &

  

          # 休眠 4个小时
          - name: Sleep
            run: sleep 4h