name: CI

on:
#   1. 每天 00:00 UTC 时间执行
  schedule:
    - cron: '0 0 * * *'
#   2. 每次 push 到 master 分支时执行
  push:
    branches:
    - master

jobs:

    build:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          # 显示端口
          - name: Show Port
            run: ip link show
          # 安装openvpn
          - name: Write OpenVPN Auth File
            run: echo -e "gitaction\ngitaction" > auth.txt
  
          - name: Write OpenVPN Config
            run: echo "${{ secrets.OVPN_CLIENT_B64 }}" | base64 -d > client.ovpn
    
          - name: Add Auth File to OpenVPN Config
            run: echo "auth-user-pass auth.txt" >> client.ovpn
    
          - name: Install OpenVPN
            run: sudo apt-get update && sudo apt-get install -y openvpn
    
          - name: Start OpenVPN
            run: sudo openvpn --config client.ovpn &
          
          - name: install wg
            run: sudo apt-get install -y wireguard-tools

          - name: Write WireGuard Private Key
            run: echo "${{ secrets.PRIVATE }}" > private.key

          - name: Setup WireGuard Config
            run: |
              sudo ip link add dev wg0 type wireguard
              sudo ip address add  dev wg0 10.0.8.10/24
              sudo wg set wg0 listen-port 51820
              sudo wg set wg0 private-key ./private.key
          - name: Add Peer
            run: |
              sudo wg set wg0 peer ${{ secrets.ENDPOINT_PUBLIC }} \
               allowed-ips 10.0.8.1/24 \
               endpoint ${{ secrets.ENDPOINT }} \
               persistent-keepalive 25 

          - name: Up WireGuard
            run: sudo ip link set up dev wg0
          
          - name: setup Forwarding
            run: |
              sudo iptables -A INPUT -p udp --dport 51820 -j ACCEPT
              sudo iptables -A FORWARD -i wg0 -j ACCEPT
              sudo iptables -A FORWARD -o wg0 -j ACCEPT
              sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE



          - name: Install Xray
            run: |
              wget https://github.com/xtls/xray-core/releases/latest/download/Xray-linux-64.zip
              unzip Xray-linux-64.zip -d xray
              chmod +x xray/xray
              sudo mv xray/xray /usr/local/bin/
              # 写入配置文件
              echo "${{ secrets.XRAY_CONFIG_B64 }}" | base64 -d > config.json
              # 启动 xray
              sudo xray run -config config.json &
          - name: Install OpenSSH Server
            run: sudo apt-get install -y openssh-server
      
          - name: Start OpenSSH Server
            run: sudo service ssh start
    
          - name: Add SSH Key
            run: |
              mkdir -p ~/.ssh
              echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
              chmod 644 ~/.ssh/id_rsa.pub
              ssh-keyscan github.com >> ~/.ssh/known_hosts
              cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  

          - name: Wait 4h no1
            run: sleep 14400

          - name: Wait 4h no2
            run: sleep 14400

          - name: Wait 4h no3
            run: sleep 14400

          - name: Wait 4h no4
            run: sleep 14400

          - name: Wait 4h no5
            run: sleep 14400

          - name: Wait 4h no6
            run: sleep 14400